import uuid
from typing import TYPE_CHECKING, NewType, override

from pydantic import BaseModel

from nexus._internal.actors.s3_client_provider import DEFAULT_S3_CLIENT_PROVIDER, S3ClientProvider
from nexus._internal.core.dsl.nodes import NodeSinks, NodeSources, Sink, SinkName, Source, SourceName, Transform
from nexus._internal.core.runtime.actor import Actor, ActorBuilder
from nexus._internal.core.runtime.actor_patterns import TransformActor
from nexus._internal.core.runtime.context_store import Context, ContextStore
from nexus._internal.core.runtime.events import PipeToBus
from nexus._internal.utils.exceptions import ActorMisconfiguredException

if TYPE_CHECKING:
    from mypy_boto3_s3 import S3Client


class PayloadCreator[Input, ExecutorPayload](Transform[Input, ExecutorPayload]):
    """
    Base transform that prepares an executor payload from a pipeline input.
    Subclasses define how the payload is created.

    sink input: pipeline input
    source created_payload: executor-ready payload
    source error: payload creation failures
    """

    input: Sink[Input]  # consumes attempts generated by retry strategy
    created_payload: Source[ExecutorPayload]  # emits the next attempt to execute,
    # with the original input and the generated payload for the executor

    def __init__(self, _id: str) -> None:
        super().__init__(_id)

        # aliases for convenience
        self.input = self.sink
        self.created_payload = self.ok

    def sinks(self) -> NodeSinks:
        return NodeSinks(sinks={SinkName("input"): self.input})

    def sources(self) -> NodeSources:
        return NodeSources(
            sources={SourceName("created-payload"): self.created_payload, SourceName("error"): self.error},
            default_source=self.created_payload,
        )


S3PresignedUrl = NewType("S3PresignedUrl", str)


class WithPresignedUrl[Input](BaseModel):
    """
    Executor payload generated by S3PresignedUrlCreator.

    Includes the original input and the generated S3 presigned URL sent to the executor.
    """

    input: Input
    presigned_url: S3PresignedUrl


class PresignedUrlCreator[Input](PayloadCreator[Input, WithPresignedUrl[Input]], ActorBuilder):
    """
    PayloadCreator that generates an S3 presigned URL and bundles it with the original input.

    sink input: pipeline input
    source created_payload: WithPresignedUrl containing the input and the presigned URL
    source error: payload creation failures
    """

    s3_client_provider: S3ClientProvider
    presigned_url_expiration_seconds: int
    s3_key: str | None
    bucket: str

    def __init__(
        self,
        _id: str,
        *,
        bucket: str,
        s3_client_provider: S3ClientProvider = DEFAULT_S3_CLIENT_PROVIDER,
        presigned_url_expiration_seconds: int = 900,
        load_s3_key: str | None = None,
        method: str,
    ) -> None:
        super().__init__(_id)
        if presigned_url_expiration_seconds <= 0:
            raise ActorMisconfiguredException("presigned_url_expiration_seconds must be > 0")
        self.s3_client_provider = s3_client_provider
        self.presigned_url_expiration_seconds = presigned_url_expiration_seconds
        self.bucket = bucket
        self.load_s3_key = load_s3_key
        self.method = method

    def build_actor(self, *, pipe_to_bus: PipeToBus, context_store: ContextStore) -> Actor:
        return PresignedUrlCreatorActor[Input](spec=self, pipe_to_bus=pipe_to_bus, context_store=context_store)


class PresignedUrlCreatorActor[Input](TransformActor[Input, WithPresignedUrl[Input]]):
    creator_spec: PresignedUrlCreator[Input]
    _s3_client: S3Client

    def __init__(
        self,
        *,
        spec: PresignedUrlCreator[Input],
        pipe_to_bus: PipeToBus,
        context_store: ContextStore,
    ) -> None:
        super().__init__(spec=spec, pipe_to_bus=pipe_to_bus, context_store=context_store)
        self.creator_spec = spec
        self._s3_client = self.creator_spec.s3_client_provider.get_client()

    @override
    def _transform(self, ctx: Context, payload: Input) -> WithPresignedUrl[Input]:
        if self.creator_spec.load_s3_key is not None:
            s3_key = ctx.copy_user_data()[self.creator_spec.load_s3_key]
        else:
            s3_key = str(uuid.uuid7())
            ctx.set_user_data(str(self.spec.id), s3_key)

        match self.creator_spec.method:
            case "PUT":
                url = self._s3_client.generate_presigned_url(
                    ClientMethod="put_object",
                    Params={"Bucket": self.creator_spec.bucket, "Key": s3_key},
                    ExpiresIn=self.creator_spec.presigned_url_expiration_seconds,
                    HttpMethod="PUT",
                )
            case "GET":
                url = self._s3_client.generate_presigned_url(
                    ClientMethod="get_object",
                    Params={"Bucket": self.creator_spec.bucket, "Key": s3_key},
                    ExpiresIn=self.creator_spec.presigned_url_expiration_seconds,
                    HttpMethod="GET",
                )
            case _:
                raise ActorMisconfiguredException(
                    f"Unsupported HTTP method for presigned URL: {self.creator_spec.method}"
                )

        return WithPresignedUrl(
            input=payload,
            presigned_url=S3PresignedUrl(url),
        )


class NoopPayloadCreator[Input](PayloadCreator[Input, Input], ActorBuilder):
    """
    PayloadCreator that passes the input through unchanged.

    sink input: pipeline input
    source created_payload: the same input, unmodified
    source error: payload creation failures
    """

    def build_actor(self, *, pipe_to_bus: PipeToBus, context_store: ContextStore) -> Actor:
        return NoopPayloadCreatorActor[Input](spec=self, pipe_to_bus=pipe_to_bus, context_store=context_store)


class NoopPayloadCreatorActor[Input](TransformActor[Input, Input]):
    @override
    def _transform(self, ctx: Context, payload: Input) -> Input:
        return payload
